/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "rgb(var(--color-echobay-50))",
          100: "rgb(var(--color-echobay-100))",
          200: "rgb(var(--color-echobay-200))",
          300: "rgb(var(--color-echobay-300))",
          400: "rgb(var(--color-echobay-400))",
          500: "rgb(var(--color-echobay-500))",
          600: "rgb(var(--color-echobay-600))",
          700: "rgb(var(--color-echobay-700))",
          800: "rgb(var(--color-echobay-800))",
          900: "rgb(var(--color-echobay-900))",
        },
        dark: {
          100: "rgb(var(--color-echobay-50))",
          200: "rgb(var(--color-echobay-100))",
          300: "rgb(var(--color-echobay-200))",
          400: "rgb(var(--color-echobay-400))",
          500: "rgb(var(--color-echobay-500))",
          600: "rgb(var(--color-echobay-600))",
          700: "rgb(var(--color-echobay-700))",
          800: "rgb(var(--color-echobay-800))",
          900: "rgb(var(--color-echobay-900))",
          950: "rgb(var(--color-echobay-900))",
        },
        echobay: {
          50: "rgb(var(--color-echobay-50))",
          100: "rgb(var(--color-echobay-100))",
          200: "rgb(var(--color-echobay-200))",
          300: "rgb(var(--color-echobay-300))",
          400: "rgb(var(--color-echobay-400))",
          500: "rgb(var(--color-echobay-500))",
          600: "rgb(var(--color-echobay-600))",
          650: "rgb(var(--color-echobay-650))",
          700: "rgb(var(--color-echobay-700))",
          800: "rgb(var(--color-echobay-800))",
          900: "rgb(var(--color-echobay-900))",
        },
        mdt: {
          bg: "hsl(var(--background))",
          card: "hsl(var(--card))",
          border: "hsl(var(--border))",
          accent: "hsl(var(--accent))",
          text: "hsl(var(--foreground))",
          muted: "hsl(var(--muted-foreground))",
        },
      },
      fontFamily: {
        sans: [
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
};
